### ISSUE TITLE
How to send message whatsapp link delphi

### ISSUE THREAD

**Issue by h4liss0n** [nickolasdeluca/UrlParser#1]
**How to send message whatsapp link delphi**

Hi, I'm having issues using UrlParser to create Urls with empty/blank spaces in parameter name/value as described below:

**Example**:
Phone: 5599999999999
text: Hello this is a test that includes  Empty/blank spaces

    https://api.whatsapp.com/send?phone=5599999999999&text=Hello this is a test that includes  Empty/blank spaces

**Comment by nickolasdeluca** [comment]
Corrigido no commit 64b38229b6f8ff052d1268551cf87fe3edc897f7.
