### ISSUE TITLE
UserName:Password

### ISSUE THREAD

**Issue by HemulGM** [nickolasdeluca/UrlParser#2]
look this sample: http://username:password@example.com/page1

**Comment by nickolasdeluca** [comment]
I'll take a look into it.

**Comment by nickolasdeluca** [comment]
Just to provide some context, in which situation would you use this URL?

**Comment by HemulGM** [comment]
Old basic auth. example
https://www.tutorialspoint.com/http-basic-authentication-url-with-in-password

**Comment by nickolasdeluca** [comment]
You can update your source file to get the new changes, you can now parse username, password and port if needed.
